// Code generated by MockGen. DO NOT EDIT.
// Source: /home/ermanur/dev/tech-assessment/ParkirPintar/presence/pkg/billingclient/client.go
//
// Generated by this command:
//
//	mockgen -source=/home/ermanur/dev/tech-assessment/ParkirPintar/presence/pkg/billingclient/client.go -destination=/home/ermanur/dev/tech-assessment/ParkirPintar/presence/_mock/pkg/billingclient/mock_billingclient.go -package=mockbillingclient -mock_names=BillingService=MockBillingService
//

// Package mockbillingclient is a generated GoMock package.
package mockbillingclient

import (
	context "context"
	apperror "parkir-pintar/services/presence/pkg/apperror"
	billingclient "parkir-pintar/services/presence/pkg/billingclient"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBillingService is a mock of BillingService interface.
type MockBillingService struct {
	ctrl     *gomock.Controller
	recorder *MockBillingServiceMockRecorder
	isgomock struct{}
}

// MockBillingServiceMockRecorder is the mock recorder for MockBillingService.
type MockBillingServiceMockRecorder struct {
	mock *MockBillingService
}

// NewMockBillingService creates a new mock instance.
func NewMockBillingService(ctrl *gomock.Controller) *MockBillingService {
	mock := &MockBillingService{ctrl: ctrl}
	mock.recorder = &MockBillingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBillingService) EXPECT() *MockBillingServiceMockRecorder {
	return m.recorder
}

// CalculateAndCreateInvoice mocks base method.
func (m *MockBillingService) CalculateAndCreateInvoice(ctx context.Context, sessionID, reservationID, driverID string, checkedInAt, checkedOutAt time.Time) (*billingclient.CreateInvoiceResult, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateAndCreateInvoice", ctx, sessionID, reservationID, driverID, checkedInAt, checkedOutAt)
	ret0, _ := ret[0].(*billingclient.CreateInvoiceResult)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CalculateAndCreateInvoice indicates an expected call of CalculateAndCreateInvoice.
func (mr *MockBillingServiceMockRecorder) CalculateAndCreateInvoice(ctx, sessionID, reservationID, driverID, checkedInAt, checkedOutAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAndCreateInvoice", reflect.TypeOf((*MockBillingService)(nil).CalculateAndCreateInvoice), ctx, sessionID, reservationID, driverID, checkedInAt, checkedOutAt)
}
