// Code generated by MockGen. DO NOT EDIT.
// Source: internal/presence/repository/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/presence/repository/init.go -destination=_mock/presence/mock_repository.go -package=mockpresence -mock_names=Presence=MockPresenceRepository
//

// Package mockpresence is a generated GoMock package.
package mockpresence

import (
	context "context"
	model "parkir-pintar/services/presence/internal/presence/model"
	apperror "parkir-pintar/services/presence/pkg/apperror"
	reflect "reflect"
	time "time"

	pgx "github.com/jackc/pgx/v5"
	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockDB is a mock of DB interface.
type MockDB struct {
	ctrl     *gomock.Controller
	recorder *MockDBMockRecorder
	isgomock struct{}
}

// MockDBMockRecorder is the mock recorder for MockDB.
type MockDBMockRecorder struct {
	mock *MockDB
}

// NewMockDB creates a new mock instance.
func NewMockDB(ctrl *gomock.Controller) *MockDB {
	mock := &MockDB{ctrl: ctrl}
	mock.recorder = &MockDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDB) EXPECT() *MockDBMockRecorder {
	return m.recorder
}

// Begin mocks base method.
func (m *MockDB) Begin(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Begin", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Begin indicates an expected call of Begin.
func (mr *MockDBMockRecorder) Begin(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Begin", reflect.TypeOf((*MockDB)(nil).Begin), ctx)
}

// Exec mocks base method.
func (m *MockDB) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockDBMockRecorder) Exec(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockDB)(nil).Exec), varargs...)
}

// QueryRow mocks base method.
func (m *MockDB) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(pgx.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockDBMockRecorder) QueryRow(ctx, sql any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockDB)(nil).QueryRow), varargs...)
}

// MockPresenceRepository is a mock of Presence interface.
type MockPresenceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPresenceRepositoryMockRecorder
	isgomock struct{}
}

// MockPresenceRepositoryMockRecorder is the mock recorder for MockPresenceRepository.
type MockPresenceRepositoryMockRecorder struct {
	mock *MockPresenceRepository
}

// NewMockPresenceRepository creates a new mock instance.
func NewMockPresenceRepository(ctrl *gomock.Controller) *MockPresenceRepository {
	mock := &MockPresenceRepository{ctrl: ctrl}
	mock.recorder = &MockPresenceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresenceRepository) EXPECT() *MockPresenceRepositoryMockRecorder {
	return m.recorder
}

// CompleteCheckOut mocks base method.
func (m *MockPresenceRepository) CompleteCheckOut(ctx context.Context, sessionID, spotID, reservationID string, checkedOutAt time.Time) *apperror.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteCheckOut", ctx, sessionID, spotID, reservationID, checkedOutAt)
	ret0, _ := ret[0].(*apperror.AppError)
	return ret0
}

// CompleteCheckOut indicates an expected call of CompleteCheckOut.
func (mr *MockPresenceRepositoryMockRecorder) CompleteCheckOut(ctx, sessionID, spotID, reservationID, checkedOutAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteCheckOut", reflect.TypeOf((*MockPresenceRepository)(nil).CompleteCheckOut), ctx, sessionID, spotID, reservationID, checkedOutAt)
}

// CreateSessionAndMarkCheckedIn mocks base method.
func (m *MockPresenceRepository) CreateSessionAndMarkCheckedIn(ctx context.Context, reservationID, driverID, spotID string, checkedInAt time.Time) (*model.Session, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSessionAndMarkCheckedIn", ctx, reservationID, driverID, spotID, checkedInAt)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CreateSessionAndMarkCheckedIn indicates an expected call of CreateSessionAndMarkCheckedIn.
func (mr *MockPresenceRepositoryMockRecorder) CreateSessionAndMarkCheckedIn(ctx, reservationID, driverID, spotID, checkedInAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSessionAndMarkCheckedIn", reflect.TypeOf((*MockPresenceRepository)(nil).CreateSessionAndMarkCheckedIn), ctx, reservationID, driverID, spotID, checkedInAt)
}

// GetReservationForCheckIn mocks base method.
func (m *MockPresenceRepository) GetReservationForCheckIn(ctx context.Context, reservationID, driverID string) (*model.Reservation, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservationForCheckIn", ctx, reservationID, driverID)
	ret0, _ := ret[0].(*model.Reservation)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetReservationForCheckIn indicates an expected call of GetReservationForCheckIn.
func (mr *MockPresenceRepositoryMockRecorder) GetReservationForCheckIn(ctx, reservationID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservationForCheckIn", reflect.TypeOf((*MockPresenceRepository)(nil).GetReservationForCheckIn), ctx, reservationID, driverID)
}

// GetSessionByID mocks base method.
func (m *MockPresenceRepository) GetSessionByID(ctx context.Context, sessionID string) (*model.Session, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, sessionID)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockPresenceRepositoryMockRecorder) GetSessionByID(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockPresenceRepository)(nil).GetSessionByID), ctx, sessionID)
}

// GetSessionForCheckOut mocks base method.
func (m *MockPresenceRepository) GetSessionForCheckOut(ctx context.Context, sessionID, driverID string) (*model.Session, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionForCheckOut", ctx, sessionID, driverID)
	ret0, _ := ret[0].(*model.Session)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetSessionForCheckOut indicates an expected call of GetSessionForCheckOut.
func (mr *MockPresenceRepositoryMockRecorder) GetSessionForCheckOut(ctx, sessionID, driverID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionForCheckOut", reflect.TypeOf((*MockPresenceRepository)(nil).GetSessionForCheckOut), ctx, sessionID, driverID)
}
