// Code generated by MockGen. DO NOT EDIT.
// Source: internal/presence/usecase/init.go
//
// Generated by this command:
//
//	mockgen -source=internal/presence/usecase/init.go -destination=_mock/presence/mock_usecase.go -package=mockpresence -mock_names=Presence=MockPresenceUsecase
//

// Package mockpresence is a generated GoMock package.
package mockpresence

import (
	context "context"
	model "parkir-pintar/services/presence/internal/presence/model"
	apperror "parkir-pintar/services/presence/pkg/apperror"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPresenceUsecase is a mock of Presence interface.
type MockPresenceUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockPresenceUsecaseMockRecorder
	isgomock struct{}
}

// MockPresenceUsecaseMockRecorder is the mock recorder for MockPresenceUsecase.
type MockPresenceUsecaseMockRecorder struct {
	mock *MockPresenceUsecase
}

// NewMockPresenceUsecase creates a new mock instance.
func NewMockPresenceUsecase(ctrl *gomock.Controller) *MockPresenceUsecase {
	mock := &MockPresenceUsecase{ctrl: ctrl}
	mock.recorder = &MockPresenceUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPresenceUsecase) EXPECT() *MockPresenceUsecaseMockRecorder {
	return m.recorder
}

// CheckIn mocks base method.
func (m *MockPresenceUsecase) CheckIn(ctx context.Context, req model.CheckInRequest) (*model.CheckInResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckIn", ctx, req)
	ret0, _ := ret[0].(*model.CheckInResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CheckIn indicates an expected call of CheckIn.
func (mr *MockPresenceUsecaseMockRecorder) CheckIn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckIn", reflect.TypeOf((*MockPresenceUsecase)(nil).CheckIn), ctx, req)
}

// CheckOut mocks base method.
func (m *MockPresenceUsecase) CheckOut(ctx context.Context, req model.CheckOutRequest) (*model.CheckOutResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOut", ctx, req)
	ret0, _ := ret[0].(*model.CheckOutResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// CheckOut indicates an expected call of CheckOut.
func (mr *MockPresenceUsecaseMockRecorder) CheckOut(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOut", reflect.TypeOf((*MockPresenceUsecase)(nil).CheckOut), ctx, req)
}

// GetSession mocks base method.
func (m *MockPresenceUsecase) GetSession(ctx context.Context, sessionID string) (*model.GetSessionResponse, *apperror.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*model.GetSessionResponse)
	ret1, _ := ret[1].(*apperror.AppError)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockPresenceUsecaseMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockPresenceUsecase)(nil).GetSession), ctx, sessionID)
}
